#!/usr/bin/env bash
# Installs nginx on the server.
#+ Nginx listens on port 80
#++ Return a page containing "Hello World!" when queried

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "World World!" > /etc/nginx/html/index/html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
