#!/usr/bin/env bash
# Installs nginx on the server and configure it to listens on port 80
#+ Return a page containing "Hello World!" when queried

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
