#!/usr/bin/env bash
# Installs nginx on the server.
#+ Nginx listens on port 80
#++ Return a page containing "Hello World!" when queried

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
